# Generated by Django 5.1.3 on 2024-12-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='recipe',
            field=models.TextField(blank=True, null=True),
        ),
    ]
