# Generated by Django 5.1.1 on 2024-10-03 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Procfile',
            new_name='Profile',
        ),
    ]
