# Generated by Django 5.1.1 on 2024-10-11 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0003_statusmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatusMessage',
        ),
    ]
